# Generated by Django 2.1.7 on 2019-04-03 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Собственник'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mysite.Post', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to=settings.AUTH_USER_MODEL, verbose_name='Собственник'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='cool',
            field=models.FloatField(default=0, verbose_name='Холодная вода'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='electric',
            field=models.FloatField(default=0, verbose_name='Электричество'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='hot',
            field=models.FloatField(default=0, verbose_name='Горячая вода'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Собственник'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Сообщение'),
        ),
    ]
