# Generated by Django 2.1.7 on 2019-03-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20180117_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='relationship',
        ),
        migrations.AddField(
            model_name='post',
            name='cool',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='electric',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='hot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='room',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Квартира'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
